[package]
name = "hkb_date"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.37"
pest = "2.7.9"
pest_derive = "2.7.9"
