[package]
name = "hkb_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.21" }
log4rs = { version = "1.3.0" }
dirs = { version = "5.0.1" }
